### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alexandru-dinu** [alexandru-dinu/code-gen#5]
- [ ] Evaluate on NAPS
- [ ] Investigate error sources on CoNaLa / Django
- [ ] Type annotations (constraints, somehow) @ train time - propagate info in AST
- [ ] Augment with python docstrings

**Comment by johnthebrave** [comment]
How's it going? :-D
